name: awsum checks

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'
      - name: configure
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/awsum-demo.pem
      - name: build
        run: go build
      - name: test
        run: go test -run=. ./...
      - name: install
        run: go install
      - name: demo deploy
        run: |
          awsum configure
          awsum instance shell --name demo "sudo yum install docker -y"
          awsum instance shell --name demo "sudo service docker start"
          awsum instance shell --name demo "sudo usermod -aG docker ec2-user"
          awsum instance shell --name demo "docker rm nginx --force"
          awsum instance shell --name demo "docker run -d -p 80:80 --name nginx nginxdemos/hello"
          awsum instance load-balance --service "nginx-demo" --name demo --port 443:80 --protocol https:http --certificate "levelshatter.com" --domain "awsum.levelshatter.com"