name: awsum checks

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'
      - name: configure
        run: |
          mkdir -p ~/.aws
          
          echo "[default]
          region = ${{ secrets.AWS_REGION }}" > ~/.aws/config
          
          echo "[default]
          aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials
          
          mkdir -p ~/.ssh
          
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/awsum-demo.pem
      - name: build
        run: go build
      - name: test
        run: go test -run=. ./...
      - name: install
        run: go install
      - name: demo deploy
        run: |
          awsum instance shell --name demo "sudo yum install docker -y
          sudo service docker start
          sudo usermod -aG docker ec2-user
          docker rm nginx --force
          docker run -d -p 80:80 --name nginx nginxdemos/hello"
          
          awsum instance load-balance --service "nginx-demo" --name demo --port 443:80 --protocol https:http --certificate "levelshatter.com"